// // const message = "І цьому рядку 25 символів"
// // console.log(message.length);


// const firstName = "John"
// const lastName = "Doe"
// const fullName = firstName + " " + lastName
// console.log(fullName);


// const room = 716
// const type = "VIP"
// // const result = fullName + " " + "заселяється в кімнату номер" + " "+ room + " " + "зі статусом " + " " + type
// // console.log(result);


// const result = `Гість ${fullName} заселяється у номер ${room} категорії ${type}`
// console.log(result);

// const quantity = 15
// console.log(`Ви купили ${quantity} холодильників`);


// let userMessage = prompt("Напиши бренд")
// userMessage = userMessage.toLowerCase()
// userMessage = userMessage.toUpperCase()
// console.log(userMessage);


// const blacklistWord1 = "спам"
// const blacklistWord2 = "розпродаж"
// const string1 = "Я арабський шейх, це спам, даю тобі мільйон"
// const string2 = "Найбільш великий РОЗПРОДАЖ цього тижня, не пропустіть"
// const string3 = "Рекламна компанія ЛАДВАЛДВПЛДВПДЬимвьи"
// console.log(string1.includes(blacklistWord1));
// console.log(string2.toLowerCase().includes(blacklistWord2));
// console.log(string3.includes(blacklistWord1));


// const school = "ITStep"
// let groupNumber = "Pront-End31"
// const name = "Kostya"

// groupNumber = groupNumber.replace("P", "F")

// const result = `Мене звати ${name}. Я навчаюсь в академії ${school} в групі ${groupNumber}`
// console.log(result);